export type Product = {
  id: string
  name: string
  price: number
  image: string
  note: string
}

// The name brands: the box with the invented wordmark painted on it.
const nameBrands: Product[] = [
  { id: 'whipped-cream', name: 'Whipped Cream', price: 3.19, image: '/images/whipped-cream.svg', note: 'Sweet whipped topping' },
  { id: 'refrigerated-biscuits', name: 'Refrigerated Biscuits', price: 2.59, image: '/images/refrigerated-biscuits.svg', note: 'Flaky refrigerated biscuits' },
  { id: 'cheese-sticks', name: 'Cheese Sticks', price: 4.49, image: '/images/cheese-sticks.svg', note: 'Mozzarella cheese sticks' },
  { id: 'cottage-cheese', name: 'Cottage Cheese', price: 3.19, image: '/images/cottage-cheese.svg', note: 'Creamy cottage cheese' },
  { id: 'margarine', name: 'Margarine', price: 4.99, image: '/images/margarine.svg', note: 'Spreadable margarine' },
  { id: 'almond-milk', name: 'Almond Milk', price: 5.49, image: '/images/almond-milk.svg', note: 'Original almond milk' },
  { id: 'donut', name: 'Donut', price: 1.19, image: '/images/donut.svg', note: 'Frosted bakery donut' },
  { id: 'cupcake', name: 'Cupcake', price: 2.99, image: '/images/cupcake.svg', note: 'Vanilla frosted cupcake' },
  { id: 'bakery-pie', name: 'Pie', price: 10.99, image: '/images/bakery-pie.svg', note: 'Fresh baked fruit pie' },
  { id: 'bakery-cake', name: 'Cake', price: 15.99, image: '/images/bakery-cake.svg', note: 'Celebration layer cake' },
  { id: 'english-muffins', name: 'English Muffins', price: 4.19, image: '/images/english-muffins.svg', note: 'Toasted English muffins' },
  { id: 'pita-bread', name: 'Pita Bread', price: 3.99, image: '/images/pita-bread.svg', note: 'Soft pita bread' },
  { id: 'bakery-cookies', name: 'Cookies', price: 5.99, image: '/images/bakery-cookies.svg', note: 'Fresh baked chocolate chip cookies' },
  { id: 'brownie', name: 'Brownie', price: 5.99, image: '/images/brownie.svg', note: 'Fudge bakery brownie' },
  { id: 'cookie-cake', name: 'Cookie Cake', price: 12.99, image: '/images/cookie-cake.svg', note: 'Chocolate chip cookie cake' },
  { id: 'banana-bread', name: 'Banana Bread', price: 6.99, image: '/images/banana-bread.svg', note: 'Fresh banana bread loaf' },
  { id: 'cinnamon-rolls', name: 'Cinnamon Rolls', price: 4.79, image: '/images/cinnamon-rolls.svg', note: 'Iced cinnamon rolls' },
  { id: 'bread-crumbs', name: 'Bread Crumbs', price: 2.29, image: '/images/bread-crumbs.svg', note: 'Seasoned bread crumbs' },
  { id: 'raisins', name: 'Raisins', price: 3.99, image: '/images/raisins.svg', note: 'Sweet dried raisins' },
  { id: 'seeds', name: 'Seeds', price: 3.79, image: '/images/seeds.svg', note: 'Mixed snack seeds' },
  { id: 'tree-nuts-peanuts', name: 'Tree Nuts / Peanuts', price: 4.49, image: '/images/tree-nuts-peanuts.svg', note: 'Roasted nut mix' },
  { id: 'oil', name: 'Oil', price: 2.99, image: '/images/oil.svg', note: 'Vegetable cooking oil' },
  { id: 'cereal', name: 'Cereal', price: 4.79, image: '/images/cereal.svg', note: 'Crunchy whole grain cereal' },
  { id: 'granola', name: 'Granola', price: 4.99, image: '/images/granola.svg', note: 'Honey oat granola' },
  { id: 'oatmeal', name: 'Oatmeal', price: 2.69, image: '/images/oatmeal.svg', note: 'Instant oatmeal packets' },
  { id: 'breakfast-bars', name: 'Breakfast Bars', price: 3.99, image: '/images/breakfast-bars.svg', note: 'Strawberry breakfast bars' },
  { id: 'protein-bars', name: 'Protein Bars', price: 5.19, image: '/images/protein-bars.svg', note: 'Chocolate protein bars' },
  { id: 'syrup', name: 'Syrup', price: 2.99, image: '/images/syrup.svg', note: 'Maple pancake syrup' },
  { id: 'honey', name: 'Honey', price: 3.99, image: '/images/honey.svg', note: 'Pure golden honey' },
  { id: 'jelly', name: 'Jelly', price: 2.49, image: '/images/jelly.svg', note: 'Strawberry jelly spread' },
  { id: 'peanut-butter', name: 'Peanut Butter', price: 5.79, image: '/images/peanut-butter.svg', note: 'Creamy peanut butter' },
  { id: 'flour', name: 'Flour', price: 2.79, image: '/images/flour.svg', note: 'All-purpose flour' },
  { id: 'sugar', name: 'Sugar', price: 3.59, image: '/images/sugar.svg', note: 'Granulated sugar' },
  { id: 'brown-sugar', name: 'Brown Sugar', price: 2.14, image: '/images/brown-sugar.svg', note: 'Light brown sugar' },
  { id: 'powdered-sugar', name: 'Powdered Sugar', price: 2.59, image: '/images/powdered-sugar.svg', note: 'Confectioners sugar' },
  { id: 'cake-mix', name: 'Cake Mix', price: 2.49, image: '/images/cake-mix.svg', note: 'Chocolate cake mix' },
  { id: 'icing', name: 'Icing', price: 2.29, image: '/images/icing.svg', note: 'Vanilla frosting' },
  { id: 'pancake-mix', name: 'Pancake Mix', price: 2.89, image: '/images/pancake-mix.svg', note: 'Buttermilk pancake mix' },
  { id: 'chocolate-chips', name: 'Chocolate Chips', price: 4.39, image: '/images/chocolate-chips.svg', note: 'Semi-sweet chocolate chips' },
  { id: 'baking-soda', name: 'Baking Soda', price: 1.29, image: '/images/baking-soda.svg', note: 'Pure baking soda' },
  { id: 'baking-powder', name: 'Baking Powder', price: 2.29, image: '/images/baking-powder.svg', note: 'Double acting baking powder' },
  { id: 'yeast', name: 'Yeast', price: 2.59, image: '/images/yeast.svg', note: 'Active dry yeast' },
  { id: 'marshmallows', name: 'Marshmallows', price: 1.99, image: '/images/marshmallows.svg', note: 'Mini marshmallows' },
  { id: 'pie-filling', name: 'Pie Filling', price: 3.99, image: '/images/pie-filling.svg', note: 'Cherry pie filling' },
  { id: 'vanilla-extract', name: 'Vanilla Extract', price: 6.79, image: '/images/vanilla-extract.svg', note: 'Pure vanilla extract' },
  { id: 'spices', name: 'Spices', price: 2.39, image: '/images/spices.svg', note: 'Ground baking spices' },
  { id: 'brownie-mix', name: 'Brownie Mix', price: 2.19, image: '/images/brownie-mix.svg', note: 'Fudge brownie mix' },
  { id: 'jello', name: 'Jello', price: 2.14, image: '/images/jello.svg', note: 'Strawberry gelatin dessert' },
  { id: 'pudding-mix', name: 'Pudding Mix', price: 2.14, image: '/images/pudding-mix.svg', note: 'Vanilla pudding mix' },
  { id: 'potato-chips', name: 'Potato Chips', price: 4.99, image: '/images/potato-chips.svg', note: 'Classic potato chips' },
  { id: 'tortilla-chips', name: 'Tortilla Chips', price: 4.94, image: '/images/tortilla-chips.svg', note: 'Crunchy tortilla chips' },
  { id: 'crackers', name: 'Crackers', price: 3.19, image: '/images/crackers.svg', note: 'Buttery snack crackers' },
  { id: 'popcorn', name: 'Popcorn', price: 3.49, image: '/images/popcorn.svg', note: 'Microwave popcorn' },
  { id: 'pretzels', name: 'Pretzels', price: 2.99, image: '/images/pretzels.svg', note: 'Twisted pretzels' },
  { id: 'graham-crackers', name: 'Graham Crackers', price: 2.99, image: '/images/graham-crackers.svg', note: 'Honey graham crackers' },
  { id: 'cookies', name: 'Cookies', price: 4.99, image: '/images/cookies.svg', note: 'Chocolate chip cookies' },
  { id: 'snack-cakes', name: 'Snack Cakes', price: 3.89, image: '/images/snack-cakes.svg', note: 'Chocolate snack cakes' },
  { id: 'cheese-crackers', name: 'Cheese Crackers', price: 4.49, image: '/images/cheese-crackers.svg', note: 'Baked cheese crackers' },
  { id: 'watermelon', name: 'Watermelon', price: 6.99, image: '/images/watermelon.svg', note: 'Fresh whole watermelon' },
  { id: 'pineapple', name: 'Pineapple', price: 3.99, image: '/images/pineapple.svg', note: 'Fresh ripe pineapple' },
  { id: 'avocado', name: 'Avocado', price: 1.29, image: '/images/avocado.svg', note: 'Fresh Hass avocado' },
  { id: 'onion', name: 'Onion', price: 1.69, image: '/images/onion.svg', note: 'Fresh yellow onion' },
  { id: 'pepper', name: 'Pepper', price: 1.69, image: '/images/pepper.svg', note: 'Fresh bell pepper' },
  { id: 'corn', name: 'Corn', price: 0.79, image: '/images/corn.svg', note: 'Fresh sweet corn' },
  { id: 'zucchini', name: 'Zucchini', price: 2.19, image: '/images/zucchini.svg', note: 'Fresh green zucchini' },
  { id: 'potatoes', name: 'Potatoes', price: 3.99, image: '/images/potatoes.svg', note: 'Fresh russet potatoes' },
  { id: 'green-beans', name: 'Green Beans', price: 3.49, image: '/images/green-beans.svg', note: 'Fresh green beans' },
  { id: 'soup', name: 'Soup', price: 2.19, image: '/images/soup.svg', note: 'Canned chicken noodle soup' },
  { id: 'beans', name: 'Beans', price: 1.79, image: '/images/beans.svg', note: 'Canned beans' },
  { id: 'canned-vegetables', name: 'Vegetables', price: 0.99, image: '/images/canned-vegetables.svg', note: 'Canned mixed vegetables' },
  { id: 'baked-beans', name: 'Baked Beans', price: 2.99, image: '/images/baked-beans.svg', note: 'Canned baked beans' },
  { id: 'chili', name: 'Chili', price: 1.99, image: '/images/chili.svg', note: 'Canned chili' },
  { id: 'canned-spaghettios', name: 'Canned Spaghetti-O', price: 2.49, image: '/images/canned-spaghettios.svg', note: 'Canned pasta rings' },
  { id: 'pasta-sauce', name: 'Pasta Sauce', price: 2.29, image: '/images/pasta-sauce.svg', note: 'Tomato basil pasta sauce' },
  { id: 'alfredo-sauce', name: 'Alfredo Sauce', price: 3.24, image: '/images/alfredo-sauce.svg', note: 'Creamy Alfredo sauce' },
  { id: 'apple-sauce', name: 'Apple Sauce', price: 3.99, image: '/images/apple-sauce.svg', note: 'Sweet apple sauce' },
  { id: 'canned-fruit', name: 'Canned Fruit', price: 2.19, image: '/images/canned-fruit.svg', note: 'Canned fruit cocktail' },
  { id: 'pickles', name: 'Pickles', price: 2.39, image: '/images/pickles.svg', note: 'Dill pickle spears' },
  { id: 'salad-dressing', name: 'Salad Dressing', price: 3.89, image: '/images/salad-dressing.svg', note: 'Ranch salad dressing' },
  { id: 'bbq-sauce', name: 'BBQ Sauce', price: 4.89, image: '/images/bbq-sauce.svg', note: 'Sweet barbecue sauce' },
  { id: 'hot-sauce', name: 'Hot Sauce', price: 5.39, image: '/images/hot-sauce.svg', note: 'Hot pepper sauce' },
  { id: 'ketchup', name: 'Ketchup', price: 4.19, image: '/images/ketchup.svg', note: 'Tomato ketchup' },
  { id: 'mayonnaise', name: 'Mayonnaise', price: 3.59, image: '/images/mayonnaise.svg', note: 'Creamy mayonnaise' },
  { id: 'mustard', name: 'Mustard', price: 1.39, image: '/images/mustard.svg', note: 'Yellow mustard' },
  { id: 'buffalo-sauce', name: 'Buffalo Sauce', price: 4.19, image: '/images/buffalo-sauce.svg', note: 'Spicy buffalo sauce' },
  { id: 'salsa', name: 'Salsa', price: 3.29, image: '/images/salsa.svg', note: 'Chunky tomato salsa' },
  { id: 'teriyaki-sauce', name: 'Teriyaki Sauce', price: 2.99, image: '/images/teriyaki-sauce.svg', note: 'Teriyaki marinade sauce' },
  { id: 'soda-can', name: 'Soda Can', price: 11.99, image: '/images/soda-can.svg', note: 'Pack of soda cans' },
  { id: 'soda-2l-bottle', name: 'Soda 2L Bottle', price: 3.49, image: '/images/soda-2l-bottle.svg', note: 'Two liter soda bottle' },
  { id: 'water', name: 'Water', price: 3.99, image: '/images/water.svg', note: 'Bottled drinking water' },
  { id: 'flavored-water', name: 'Flavored Water', price: 0.94, image: '/images/flavored-water.svg', note: 'Fruit flavored water' },
  { id: 'sparkling-water', name: 'Sparkling Water', price: 1.49, image: '/images/sparkling-water.svg', note: 'Sparkling mineral water' },
  { id: 'apple-juice', name: 'Apple Juice', price: 2.69, image: '/images/apple-juice.svg', note: '100% apple juice' },
  { id: 'lemonade', name: 'Lemonade', price: 2.89, image: '/images/lemonade.svg', note: 'Fresh lemonade' },
  { id: 'cranberry-juice', name: 'Cranberry Juice', price: 2.79, image: '/images/cranberry-juice.svg', note: 'Cranberry juice cocktail' },
  { id: 'energy-drink', name: 'Energy Drink', price: 2.99, image: '/images/energy-drink.svg', note: 'Energy drink can' },
  { id: 'coffee', name: 'Coffee', price: 3.99, image: '/images/coffee.svg', note: 'Ground coffee' },
  { id: 'tea', name: 'Tea', price: 2.99, image: '/images/tea.svg', note: 'Tea bags' },
  { id: 'sports-drink', name: 'Sports Drink', price: 1.79, image: '/images/sports-drink.svg', note: 'Electrolyte sports drink' },
  { id: 'drink-mix-powder', name: 'Drink Mix Powder', price: 1.29, image: '/images/drink-mix-powder.svg', note: 'Fruit drink powder mix' },
  { id: 'protein-shakes', name: 'Protein Shakes', price: 3.89, image: '/images/protein-shakes.svg', note: 'Ready-to-drink protein shake' },
  { id: 'thin-crust-pizza', name: 'Thin Crust Pizza', price: 2.99, image: '/images/thin-crust-pizza.svg', note: 'Thin crust cheese pizza' },
  { id: 'deluxe-pizza', name: 'Deluxe Pizza', price: 8.99, image: '/images/deluxe-pizza.svg', note: 'Deluxe supreme pizza' },
  { id: 'frozen-lasagna', name: 'Lasagna', price: 22.99, image: '/images/frozen-lasagna.svg', note: 'Family-size frozen lasagna' },
  { id: 'ravioli', name: 'Ravioli', price: 4.99, image: '/images/ravioli.svg', note: 'Cheese ravioli' },
  { id: 'frozen-dinner', name: 'Frozen Dinner', price: 1.89, image: '/images/frozen-dinner.svg', note: 'Ready-to-heat dinner' },
  { id: 'pizza-rolls', name: 'Pizza Rolls', price: 12.89, image: '/images/pizza-rolls.svg', note: 'Pepperoni pizza rolls' },
  { id: 'chicken-nuggets', name: 'Chicken Nuggets', price: 13.59, image: '/images/chicken-nuggets.svg', note: 'Crispy chicken nuggets' },
  { id: 'waffles', name: 'Waffles', price: 3.69, image: '/images/waffles.svg', note: 'Homestyle frozen waffles' },
  { id: 'breakfast-sandwich', name: 'Breakfast Sandwich', price: 8.49, image: '/images/breakfast-sandwich.svg', note: 'Egg and cheese breakfast sandwich' },
  { id: 'frozen-fries', name: 'Frozen Fries', price: 4.54, image: '/images/frozen-fries.svg', note: 'Crispy frozen fries' },
  { id: 'frozen-dinner-rolls', name: 'Dinner Rolls', price: 6.89, image: '/images/frozen-dinner-rolls.svg', note: 'Frozen dinner rolls' },
  { id: 'ice-cream', name: 'Ice Cream', price: 5.99, image: '/images/ice-cream.svg', note: 'Vanilla ice cream' },
  { id: 'popsicles', name: 'Popsicles', price: 2.49, image: '/images/popsicles.svg', note: 'Fruit flavored popsicles' },
  { id: 'frozen-vegetables', name: 'Frozen Vegetables', price: 2.99, image: '/images/frozen-vegetables.svg', note: 'Mixed frozen vegetables' },
  { id: 'catfish', name: 'Catfish', price: 11.99, image: '/images/catfish.svg', note: 'Fresh catfish fillet' },
  { id: 'salmon', name: 'Salmon', price: 6.5, image: '/images/salmon.svg', note: 'Fresh Atlantic salmon' },
  { id: 'rainbow-trout', name: 'Rainbow Trout', price: 6.5, image: '/images/rainbow-trout.svg', note: 'Fresh rainbow trout' },
  { id: 'cod', name: 'Cod', price: 15.99, image: '/images/cod.svg', note: 'Wild-caught cod fillet' },
  { id: 'tuna-steaks', name: 'Tuna Steaks', price: 8, image: '/images/tuna-steaks.svg', note: 'Fresh tuna steaks' },
  { id: 'canned-tuna', name: 'Canned Tuna', price: 2.99, image: '/images/canned-tuna.svg', note: 'Chunk light tuna' },
  { id: 'tilapia', name: 'Tilapia', price: 7.99, image: '/images/tilapia.svg', note: 'Fresh tilapia fillet' },
  { id: 'lobster-tail', name: 'Lobster Tail', price: 11, image: '/images/lobster-tail.svg', note: 'Cold water lobster tail' },
  { id: 'shrimp', name: 'Shrimp', price: 18.99, image: '/images/shrimp.svg', note: 'Large peeled shrimp' },
  { id: 'ground-beef', name: 'Ground Beef', price: 6.99, image: '/images/ground-beef.svg', note: 'Fresh ground beef' },
  { id: 'steak', name: 'Steak', price: 9.5, image: '/images/steak.svg', note: 'Fresh beef steak' },
  { id: 'roast', name: 'Roast', price: 10.49, image: '/images/roast.svg', note: 'Beef roast' },
  { id: 'pork-chops', name: 'Pork Chops', price: 3.49, image: '/images/pork-chops.svg', note: 'Fresh pork chops' },
  { id: 'bacon', name: 'Bacon', price: 4.74, image: '/images/bacon.svg', note: 'Smoked bacon' },
  { id: 'sausage-patties', name: 'Sausage Patties', price: 3.99, image: '/images/sausage-patties.svg', note: 'Breakfast sausage patties' },
  { id: 'chicken', name: 'Chicken', price: 9.99, image: '/images/chicken.svg', note: 'Fresh whole chicken' },
  { id: 'chicken-tenders', name: 'Chicken Tenders', price: 2.99, image: '/images/chicken-tenders.svg', note: 'Chicken breast tenders' },
  { id: 'chicken-wings', name: 'Chicken Wings', price: 6.99, image: '/images/chicken-wings.svg', note: 'Fresh chicken wings' },
  { id: 'sausage-links', name: 'Sausage Links', price: 7.79, image: '/images/sausage-links.svg', note: 'Pork sausage links' },
  { id: 'hot-dogs', name: 'Hot Dogs', price: 5.29, image: '/images/hot-dogs.svg', note: 'Classic hot dogs' },
  { id: 'pepperoni', name: 'Pepperoni', price: 5.49, image: '/images/pepperoni.svg', note: 'Sliced pepperoni' },
  { id: 'deli-meat', name: 'Deli Meat', price: 5.99, image: '/images/deli-meat.svg', note: 'Sliced deli meat' },
  { id: 'ham', name: 'Ham', price: 10.99, image: '/images/ham.svg', note: 'Smoked ham' },
  { id: 'turkey', name: 'Turkey', price: 6.79, image: '/images/turkey.svg', note: 'Turkey breast' },
  { id: 'meatballs', name: 'Meatballs', price: 8.49, image: '/images/meatballs.svg', note: 'Italian-style meatballs' },
  { id: 'lamb-chops', name: 'Lamb Chops', price: 16.99, image: '/images/lamb-chops.svg', note: 'Premium lamb chops' },
  { id: 'bison', name: 'Bison', price: 11.99, image: '/images/bison.svg', note: 'Ground bison' },
  {
    id: 'apple',
    name: 'Apple',
    price: 0.89,
    image: '/images/apple.svg',
    note: 'Fresh red apple',
  },
  {
    id: 'banana',
    name: 'Banana',
    price: 0.59,
    image: '/images/banana.svg',
    note: 'Single ripe banana',
  },
  {
    id: 'bread',
    name: 'Bread',
    price: 2.79,
    image: '/images/bread.svg',
    note: 'Soft bread loaf',
  },
  {
    id: 'hotdog-buns',
    name: 'Hot Dog Buns',
    price: 1.89,
    image: '/images/hotdog-buns.svg',
    note: 'Soft hot dog buns',
  },
  {
    id: 'hamburger-buns',
    name: 'Hamburger Buns',
    price: 2.89,
    image: '/images/hamburger-buns.svg',
    note: 'Soft hamburger buns',
  },
  {
    id: 'dinner-rolls',
    name: 'Dinner Rolls',
    price: 4.49,
    image: '/images/dinner-rolls.svg',
    note: 'Warm dinner rolls',
  },
  {
    id: 'tortillas',
    name: 'Tortillas',
    price: 1.99,
    image: '/images/tortillas.svg',
    note: 'Soft flour tortillas',
  },
  {
    id: 'taco-shells',
    name: 'Taco Shells',
    price: 2.89,
    image: '/images/taco-shells.svg',
    note: 'Crunchy taco shells',
  },
  {
    id: 'bagels',
    name: 'Bagels',
    price: 4.99,
    image: '/images/bagels.svg',
    note: 'Plain bakery bagels',
  },
  {
    id: 'muffins',
    name: 'Muffins',
    price: 5.99,
    image: '/images/muffins.svg',
    note: 'Fresh blueberry muffins',
  },
  {
    id: 'pizza-crust',
    name: 'Pizza Crust',
    price: 4.79,
    image: '/images/pizza-crust.svg',
    note: 'Ready-to-bake pizza crust',
  },
  {
    id: 'cheddar-cheese-slices',
    name: 'Cheddar Cheese Slices',
    price: 2.29,
    image: '/images/cheddar-cheese-slices.svg',
    note: 'Sliced cheddar cheese',
  },
  {
    id: 'mozzarella-cheese',
    name: 'Mozzarella Cheese',
    price: 2.99,
    image: '/images/mozzarella-cheese.svg',
    note: 'Shredded mozzarella cheese',
  },
  {
    id: 'yogurt',
    name: 'Yogurt',
    price: 1.99,
    image: '/images/yogurt.svg',
    note: 'Creamy strawberry yogurt',
  },
  {
    id: 'eggs',
    name: 'Eggs',
    price: 1.59,
    image: '/images/eggs.svg',
    note: 'Dozen large eggs',
  },
  {
    id: 'sour-cream',
    name: 'Sour Cream',
    price: 2.89,
    image: '/images/sour-cream.svg',
    note: 'Classic sour cream',
  },
  {
    id: 'cream-cheese',
    name: 'Cream Cheese',
    price: 3.59,
    image: '/images/cream-cheese.svg',
    note: 'Original cream cheese',
  },
  {
    id: 'butter',
    name: 'Butter',
    price: 1.79,
    image: '/images/butter.svg',
    note: 'Salted butter sticks',
  },
  {
    id: 'macaroni-and-cheese',
    name: 'Macaroni & Cheese',
    price: 1.39,
    image: '/images/macaroni-and-cheese.svg',
    note: 'Boxed macaroni and cheese',
  },
  {
    id: 'pasta',
    name: 'Pasta',
    price: 1.29,
    image: '/images/pasta.svg',
    note: 'Penne pasta',
  },
  {
    id: 'ramen-noodles',
    name: 'Ramen Noodles',
    price: 0.59,
    image: '/images/ramen-noodles.svg',
    note: 'Instant ramen noodles',
  },
  {
    id: 'rice',
    name: 'Rice',
    price: 2.79,
    image: '/images/rice.svg',
    note: 'Long grain white rice',
  },
  {
    id: 'boxed-mashed-potatoes',
    name: 'Boxed Mashed Potatoes',
    price: 2.99,
    image: '/images/boxed-mashed-potatoes.svg',
    note: 'Creamy mashed potato mix',
  },
  {
    id: 'grapes',
    name: 'Grapes',
    price: 1.99,
    image: '/images/grapes.svg',
    note: 'Fresh seedless grapes',
  },
  {
    id: 'strawberries',
    name: 'Strawberries',
    price: 6.99,
    image: '/images/strawberries.svg',
    note: 'Fresh strawberries',
  },
  {
    id: 'blueberries',
    name: 'Blueberries',
    price: 3.99,
    image: '/images/blueberries.svg',
    note: 'Fresh blueberries',
  },
  {
    id: 'oranges',
    name: 'Oranges',
    price: 1.39,
    image: '/images/oranges.svg',
    note: 'Fresh oranges',
  },
  {
    id: 'lettuce',
    name: 'Lettuce',
    price: 2.79,
    image: '/images/lettuce.svg',
    note: 'Fresh green lettuce',
  },
  {
    id: 'tomato',
    name: 'Tomato',
    price: 2.99,
    image: '/images/tomato.svg',
    note: 'Fresh tomato',
  },
  {
    id: 'carrots',
    name: 'Carrots',
    price: 2.99,
    image: '/images/carrots.svg',
    note: 'Fresh carrots',
  },
  {
    id: 'orangejuice',
    name: 'Orange Juice',
    price: 2.75,
    image: '/images/orangejuice.svg',
    note: 'Carton of orange juice',
  },
  {
    id: 'milk',
    name: 'Milk',
    price: 3.29,
    image: '/images/milk.svg',
    note: 'Whole milk, 1 gallon',
  },
  {
    id: 'soymilk',
    name: 'Soy Milk',
    price: 3.49,
    image: '/images/soymilk.svg',
    note: 'Plant-based milk',
  },
]

// --------------------------------------------------- the CG store brand line
//
// Every name brand has a ClassGrocery twin: the same product, in the same
// packaging, printed in a plainer palette and priced a little lower. It is a
// separate product with its own id, so a store can carry one brand, the other,
// or both side by side, and a receipt can tell them apart.
//
// The artwork is generated from the name-brand file by scripts/make-cg-images.mjs.

/** What marks a product id as belonging to the store-brand line. */
export const storeBrandSuffix = '-cg'

/** A CG item costs 15% less than the name brand beside it. */
export const storeBrandDiscount = 0.85

export function isStoreBrand(productId: string) {
  return productId.endsWith(storeBrandSuffix)
}

/** 'milk-cg' -> 'milk'. Returns the id unchanged for a name brand. */
export function nameBrandIdOf(productId: string) {
  return isStoreBrand(productId) ? productId.slice(0, -storeBrandSuffix.length) : productId
}

export function storeBrandIdOf(productId: string) {
  return isStoreBrand(productId) ? productId : productId + storeBrandSuffix
}

export function storeBrandPrice(nameBrandPrice: number) {
  return Math.round(nameBrandPrice * storeBrandDiscount * 100) / 100
}

function storeBrandOf(product: Product): Product {
  return {
    id: storeBrandIdOf(product.id),
    name: `CG ${product.name}`,
    price: storeBrandPrice(product.price),
    image: `/images/cg/${product.id}.svg`,
    note: product.note,
  }
}

export const products: Product[] = [...nameBrands, ...nameBrands.map(storeBrandOf)]

export const productById = Object.fromEntries(products.map((product) => [product.id, product]))
